Support to additional kinds, error handling in case IsNotRegisteredError
postfinance/kuota-calc pull request #10
Opened 2021-12-03 14:22 UTC by lzecca78

Hi! 
the current PR will introduce the following kinds: 

* apps/v1 - DaemonSet
* batch/v1 - Cronjob
* batch/v1 - Job
* v1 - Pod

On top of that,  I've handled the cases in which the resources present in the yaml are not registered, and instead of failing, it raises an error.

2021-12-05 09:07 UTC, lzecca78 commented
hi @ghouscht, I saw that is failing the linter, I  fix it asap. 
The one if failing about the test is because it is using golang 1.15, while I've updated the golang version (and all the libraries) to golang 1.17. In the latest commit, I've fix the lining (hopefully) and forced the `action/setup-go` to use the golang 1.17 version

2021-12-06 05:45 UTC, ghouscht commented
> hi @ghouscht, I saw that is failing the linter, I fix it asap. The one if failing about the test is because it is using golang 1.15, while I've updated the golang version (and all the libraries) to golang 1.17. In the latest commit, I've fix the lining (hopefully) and forced the `action/setup-go` to use the golang 1.17 version

That's ok, thank you. Will review the changes later on today.

2021-12-06 10:25 UTC, ghouscht requested changes
Looks very good to me, just some small nits (see comments) and one small request: Can you please include the newly supported resources in the last section of the README? Maybe also with a hint regarding Daemonsets?

Thank you very much!

2021-12-06 10:25 UTC, ghouscht commented on internal/calc/daemonset.go
> +			MaxReplicas: 0,
Hmm since we don't know the number of nodes a potential cluster has we can't determine the number of replicas a Daemonset has. Maybe it is worth leaving a warning here?

2021-12-06 10:25 UTC, ghouscht commented on internal/calc/job.yaml
> +          restartPolicy: OnFailure
This file is not used, can you please remove it?

2021-12-06 10:25 UTC, ghouscht commented on internal/calc/calc.go
> +		version = gvk.Version
A bit hard to read the combination of if/else branches, but ok since I currently can't see a simpler solution.

2021-12-06 10:33 UTC, lzecca78 commented on internal/calc/daemonset.go
> +			MaxReplicas: 0,
in a Deaemonset replicas are not provided, the ratio behind Daemonset is 1 pod for each node : https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/

2021-12-06 10:35 UTC, lzecca78 commented on internal/calc/job.yaml
> +          restartPolicy: OnFailure
sorry, i forgot to remove it!

2021-12-06 10:36 UTC, lzecca78 commented on internal/calc/calc.go
> +		version = gvk.Version
yeah, you're right, not very friendly. Probably the only solution is to extract a function to make it simpler, but i dunno if this will make it better or not

2021-12-06 10:39 UTC, ghouscht commented on internal/calc/calc.go
> +		version = gvk.Version
Just leave it as it is, ok for me.

2021-12-06 10:46 UTC, lzecca78 commented on internal/calc/daemonset.go
> +			MaxReplicas: 0,
Sorry probably i didn't read your comment carefully: i was thinking the quota is useful for namespace quota, so i was supposing that getting the resource with 1 replica, was ok. Am i wronging the assumption?

2021-12-06 11:06 UTC, ghouscht approved these changes

2021-12-06 11:59 UTC, merged